### PR TITLE
Supplemented with rules for ProGuard

### PR DESCRIPTION
**Pull request by arok**

### CODE REVIEW

**Comment by sockeqwe** [comment]
I think that the classes Annotated with `@Arg` don't have to be kept (see #12). Actually, I think that `AutoFragmentArgInjector` (which is a mapping class generated by Annotation Processing) is the only Class that is not allowed to be obfuscated by proguard since that class will be loaded by class name by using reflections

**Comment by arok** [comment]
In my project this rules not enough. When FragmentArgs.inject() is called it not initialize my fields it's stay NULL.

**Comment by sockeqwe** [comment]
Hm, with latest version of fragmentargs `2.1.2`? Please note that the compiler must be on latest version as well.

**Comment by arok** [comment]
And yes, the latest version has no this issue. Thanks.

**Pull request closed without merging**
